---
- name: activity 1
  hosts: webservers
  become: true
  tasks:

  - name: update docker.io (state=present is optional)
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: Install python3-pip (state=present is optional)
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install docker via pip (state=present is optional)
    pip:
      name: docker
      state: present

  - name: Install dvwa via docker-container (state=present is optional)
    community.general.docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      published_ports: 80:80
      state: started
      restart_policy: always

  - name: Start docker when vm starts (state=present is optional)
    ansible.builtin.systemd:
      name: docker
      enabled: yes
